---
title: "Fazit"
---

> Da Frauen nicht nur Opfer bisheriger Geschichte sind und sein wollen, gehört zur Frauenforschung von Anbeginn auch die Suche nach ihrem Anteil am Zivilisationsprozess, der in der von Männern geschriebenen Geschichte ausgespart worden ist. Dieser Rückblick ist gegenwarts- und zukunftsbezogen: Mit welchen Strategien können Frauen die Welt zu ihren Gunsten und zum Vorteil aller verändern, welche weiblichen Vorbilder gibt es für ihre Emanzipationsanstrengungen?[^1]

Antagonistisch zum Erinnern spielt das Vergessen eine wesentliche Rolle. Vergessen nach Halbwachs bedeutet nämlich nicht das Löschen oder Verschwinden von Informationen, sondern besitzt das Potenzial, neue und andersartige Erinnerungen zu schaffen, Erinnerungen neu zu interpretieren, anzupassen und umzuordnen. Die vorliegende Untersuchung legt nahe, dass die *Gastarbeiterin* im institutionellen Web-Gedächtnis präsent ist – jedoch vorwiegend im generischen Maskulinum, selten als Individuum und kaum in gewerkschaftlichen Kontexten. Die Ergebnisse der Web- wie Archivanalysen haben eine Tendenz des institutionellen Vergessens offenbart – wobei nicht zu vernachlässigen ist, dass die untersuchten URLs keine gesamtheitliche Repräsentation noch ein Abbild des Web-Gedächtnisses darstellen können. Eine Gegenbewegung zum institutionellen Vergessen bildet das Aufkommen von genderinklusiver Sprache und verändert damit auch, an *wen* gedacht wird oder zumindest lange nicht gedacht wurde.

Mit dem Migrationsprozess in Deutschland veränderte sich die Gesellschaft zu einer pluralistischen Zusammensetzung und erweiterte damit auch den Migrationsdiskurs. Dass sich Geschichtsschreibungen geöffnet haben, ist nicht etwa deutschen Institutionen, sondern vor allem (post-)migrantischen Stimmen und Perspektiven zu verdanken. Dazu gehören eben auch die in Deutschland lebenden Nachkommen der *Gastarbeitenden*, inspiriert von Familien- und Kollektivgeschichten – wie auch im Falle meiner vorliegenden wissenschaftlichen Ausarbeitung. Es gilt zudem die Geschichtsschreibung aus einer intersektional-feministischen Perspektive zu rekonstruieren, um hegemonial entstandene Gedächtnis- und Erinnerungslücken zu schließen. Oder um es in Espositos Worten zu fassen: „Es ist ratsam […] die Erinnerungen zu vermehren. Man kann nämlich nicht zum ursprünglichen Zustand des Informationsmangels zurückkehren."[^2] Eine (post-)migrantische wie intersektional gedachte Rekonstruktion der Vergangenheit sowie die (digitale) Archivierung dessen schaffen nachhaltig Gegennarrative und widersetzen sich institutionellen Unsichtbarmachungen. Das zeigt sich nicht zuletzt in der Archivierungsanalyse: Während ein PDF der Otto-Brenner-Stiftung im Live-Web längst nicht mehr existiert, hat die Wayback Machine es zehnmal archiviert. Ein Artikel von ver.di über *Gastarbeitende* wurde hingegen nie gesichert und wäre bei einer Löschung unwiderruflich verloren. Archivierungen, ob analog oder digital, sind essenzielle Praktiken, um fortlaufende Diskriminierungsstrukturen und Machtasymmetrien historisch zu verorten und auf gegenwärtige Forschungen anzuwenden.

An dieser Stelle ist zu erwähnen, dass nicht von einer Großkategorie *Gastarbeiterin*, geschweige denn *Frau* gesprochen werden. Es wäre schließlich verantwortungslos zu behaupten, es gäbe eine einheitlich weibliche Erfahrung. Aus einer intersektionalen Perspektive würde sich dies als unterkomplex erweisen. Der Begriff *Gastarbeiterin* ist soziopolitisch voreingenommen. Dennoch birgt die Wieder-Aneignung des Begriffs das Potenzial für eine emanzipatorische Neudefinition und setzt die *Gastarbeiterin* zurück in die Sphäre der Erinnerung. 

[^1]: Becker-Schmidt, Regina: „Frauenforschung, Geschlechterforschung, Geschlechterverhältnisforschung". In: dies./Knapp, Gudrun-Axeli (2000, Hg.): *Feministische Theorie zur Einführung*. Hamburg: Junius Verlag. S. 34.

[^2]: Esposito: „Die Formen des Web-Gedächtnisses”. S. 95.
