---
title: "Gastarbeiterinnen – die stillsten aller Reserven?"
---

## Exkurs: Geschichte der sogenannten Gastarbeit

Nach ihrer Gründung im Jahr 1949 sah sich die Bundesrepublik Deutschland, in einer Phase der Hochkonjunktur, mit Arbeitskräftemangel konfrontiert. Betroffen waren unter anderem die Landwirtschaft, der Bergbau, die Stahl- und Textilindustrie sowie der Dienstleistungssektor. Abhilfe sollte das Anwerben von (geringverdienenden) Arbeitskräfte aus dem europäischen Ausland schaffen. So kam es 1955 zum ersten bilateralen Abkommen mit Italien, gefolgt von weiteren Abkommen mit Griechenland und Spanien (1960), der Türkei (1961), Portugal (1964) und Jugoslawien (1968) bis im Jahr 1973 der Anwerbestopp veranlasst wurde. Was anfänglich als Idee einer staatlich-regulierten Migration für temporäre Arbeits- und Aufenthaltsverhältnisse angesiedelt war, resultierte darin, dass Deutschland einen Einwanderungsprozess erlebte.[^3] Denn die Prognose, die *Gastarbeitenden* würden binnen kurzer Zeit wieder das Land verlassen, trat nur bedingt ein. Zwar ging die Zahl der ausländischen Arbeitnehmer:innen zunächst zurück, doch die Dichte der ausländischen Bewohner:innen, insbesondere aus der Türkei, nahm durch den Anwerbestopp bis Mitte der 1970er Jahre zu. Schließlich standen sie vor der endgültigen Entscheidung, entweder in ihre Heimatländer zurückzukehren oder ihre Familien nachziehen zu lassen. In der Türkei warteten einerseits hohe Arbeitslosigkeit, politische Instabilität und Gewalt sowie die Folgen des Militärputschs auf sie.[^4] Andererseits sorgten die hohen Lebenshaltungskosten in Deutschland dafür, dass Sparziele und damit auch der Traum von Wohlstand in der Heimat (noch) nicht erreicht wurden. Trotz des Rückkehrhilfegesetzes – eine finanzielle Förderung für die freiwillige Rückkehr der *Gastarbeitenden* – hatten einige inzwischen ihren Lebensmittelpunkt in der Bundesrepublik gefunden.[^5]

## Weibliche Erwerbsarbeit in der Bundesrepublik Deutschland

Die Bundesrepublik Deutschland konnte in Zeiten des wirtschaftlichen Aufschwungs ab den 1950er Jahren ihren Bedarf nicht mit einheimischen männlichen Arbeitskräften decken. Während jungen ledigen Frauen ohne Familienpflichten im Laufe des Jahrzehnts inzwischen das Recht auf Erwerbsarbeit zustand[^6], war die Mobilisierung der sogenannten *stillen Reserve* – also nichterwerbstätige verheiratete Frauen und Mütter – zwar notwendig, aber aus familienpolitischer Sicht umstritten.[^7] Dies ist darauf zurückzuführen, dass noch die Vorstellung des tradierten Ernährer-Hausfrau-Modells vorherrschte, welches Frauen primär in ihrer Rolle als Ehefrau und Mutter verortete.[^8] Daraus etablierte sich die Teilzeitbeschäftigung, sodass Ehefrauen und Mütter nun in den deutschen Arbeitsmarkt integriert werden und gleichzeitig ihren ‚weiblichen Pflichten' der Sorgearbeit nachkommen konnten.[^9] Mit dem gleichzeitig verlaufenden Prozess der Anwerbung von ausländischen Arbeitskräften sowie des neueingeführten Teilzeit-Erwerbsmodells wurde, so Mattes, eine Doppelstrategie gefahren. Die Anwerbung richtete sich nämlich nicht nur an Männer, sondern auch gezielt an Frauen und Mütter aus dem Ausland.[^10]

## Anwerbung von weiblichen Arbeitsmigrantinnen

Die Bundesrepublik unternahm eine geschlechterspezifische Arbeitsanwerbung, bei der junge ledige Frauen aus dem Ausland gefragt waren, denn „Unverheiratete und Kinderlose [galten] als belastbarer, mobiler und zeitlich flexibler als Verheiratete".[^11] Im Vergleich zu männlichen *Gastarbeitern*, die für körperlich schwere Tätigkeiten im Bergbau oder der Gießerei eingesetzt wurden[^12], wurden *Gastarbeiterinnen* dringend für die Niedriglohnbranche benötigt – etwa in der Textil-, Nahrungsmittel-, Elektro- und Metallverarbeitungsindustrie. Es galten geschlechtsspezifische Arbeitsteilungen, die definierten, dass Frauen eher für leichte Arbeiten mit Bezug zu Haus- und Sorgetätigkeiten geeignet seien.[^13] In elektrotechnischen Betrieben waren weibliche Arbeitskräfte aufgrund ihres vermeintlichen Geschlechtercharakters[^14] – Frauen seien fingerfertig und feinmotorisch talentiert – beliebt.[^15] Aufgrund dessen wurden *Gastarbeiterinnen* insbesondere in der Akkord- und Fließbandarbeit sowie Textilarbeit eingesetzt.

Während die Vereinbarkeit von Mutterschaft und Erwerbsarbeit in der Bundesrepublik vielfach diskutiert wurde, wurde der Aspekt des Familienstands bei der *Gastarbeiterin* vorwiegend ignoriert oder umgedeutet. Märksch illustriert, dass verheiratete Frauen und Mütter, wenn sie ohne Ehemann und Kinder nach Deutschland kamen, in Statistiken als lediggehend geführt wurden.[^16] „Der Fakt, dass [migrantische] Frauen als ‚lediggehend' geführt wurden" argumentiert Märksch, „legen den Verdacht nahe, dass die Beschäftigung von Migrantinnen nicht mit dem Thema ‚Mütterarbeit' in Verbindung gebracht werden sollte".[^17] Auffällig erscheint dabei eine staatlich-politische Doppelmoral bezüglich weiblicher Erwerbsarbeit zwischen deutschen und ausländischen Frauen. Einerseits wurde der Schutz der deutsch-bürgerlichen Hausfrau und Mutter vor einer Doppelbelastung durch Sorge- und Erwerbsarbeit propagiert, andererseits wurde dieser Schutz den *Gastarbeiterinnen* (in-)direkt verwehrt.[^18] Dies führte letztlich zu neuen Hierarchieverhältnissen zwischen Frauen, basierend auf den Kategorien Klassenzugehörigkeit und Ethnie.

## Frau, Arbeiterin, Migrantin

Weibliche Vollzeit-Erwerbsarbeit in Deutschland war statistisch gesehen keine ausschließliche Frage des Familienstands, sondern auch eine Frage der Klasse. Während die Beschäftigung bürgerlich-situierter verheirateter Frauen und Mütter minimiert werden sollte, lag die Vollzeitbeschäftigung der weiblichen Arbeiterinnenklasse am höchsten.[^19] Auch lagen die Löhne zwischen deutschen und ausländischen Arbeiterinnen näher beieinander als beispielsweise zwischen ausländischen Frauen und Männern. Obwohl die Öffnung des Arbeitsmarktes für Frauen in gewissem Maß finanzielle Unabhängigkeit bedeutete, schaffte das noch längst keine Gleichstellung der Geschlechter. Patriarchal-geprägte Hierarchien sorgten auch auf dem Arbeitsmarkt für Benachteiligungen, die sich in geschlechtsspezifischer Lohndiskriminierung äußerte. Dass Frauentätigkeiten vorgeblich leicht körperliche bis einfache Arbeit seien, wurde als Legitimation dafür genutzt, Frauen der sogenannten Leichtlohngruppen zuzuordnen und ihre Löhne niedrig zu halten.[^20]

Neben den bereits existierenden Diskriminierungsachsen Geschlecht und Klasse kam mit der Anwerbung von *Gastarbeitenden* ein weiteres Kriterium hinzu – die Ethnizität. Im Diskurs der Bundesrepublik der 1970er Jahre, die sich selbst als modern und zivilisiert begriff, wurde das konstruierte Selbstbild der emanzipierten westlichen Frau in Abgrenzung zu einem konstruierten Fremdbild der ‚defizitären, unterdrückten und rückständigen' migrantischen Frau entworfen.[^21] Interessant ist dabei die Paradoxie, dass in Deutschland zeitgleich noch tradierte Geschlechterrollen und geschlechterspezifische Arbeitsteilungen vorherrschten. Beschäftigungsquoten der 1970er Jahre zeigen, dass 71,6% der migrantischen Frauen in Deutschland berufstätig waren, während nur 37,7% der deutschen Frauen einer Erwerbstätigkeit nachgingen.[^22] Darauf stellen Bednarz-Braun und Heß-Meining in den Raum, dass beispielsweise „türkische Migrantinnen [...] sehr viel ‚fortschrittlicher' waren, weil sie aufgrund ihrer eigenen Erwerbstätigkeit und materiellen Absicherung von einem männlichen Partner relativ unabhängig und damit entscheidungsautonom waren, zumal dann, wenn sie als ledige Frauen einreisten oder ohne ihre Ehemänner"[^23]. Vielmehr seien es die juristischen sowie institutionellen Regelungen gewesen, die Rechte und Handlungsräume der migrantischen Frauen eingrenzten – wie etwa die Ausländergesetzgebung, die prekäre Entlohnung nach Leichtlohngruppen oder die fehlende Arbeitserlaubnis im Rahmen des Familiennachzugs.[^24] Es lässt sich schlussfolgern, dass *Gastarbeiterinnen* strukturell sowohl für ihr Geschlecht als auch für ihre ethnische Zugehörigkeit diskriminiert und als günstige Arbeitskräfte in die Unterschicht kategorisiert wurden.

## Öffentliche Wahrnehmung von der Gastarbeiterin

Das Klischee des männlichen *Gastarbeiters*, der Frau und Kinder in die Bundesrepublik nachholte, entspricht nur einer partiellen Wahrheit. „Ungeachtet ihrer zahlenmäßigen Präsenz" so Kürten, „wurden ausländische Arbeitnehmerinnen von der westdeutschen Öffentlichkeit in der Regel kaum wahrgenommen"[^25]. Das medial vermittelte Bild von *Gastarbeitenden* sei vorranging jung, schwarzhaarig und männlich gewesen, während Frauen „entweder nur implizit in der Rolle des nachgeordneten Familienmitglieds gedacht oder als Opfer der Umstände, das sich aufgrund der materiellen Not ihrer Familien zur Arbeitsmigration gezwungen sahen"[^26]. Damit entstand in der deutschen Mehrheitsgesellschaft der Stereotyp der ‚passiven' migrantischen Frau. Dabei wird unterbelichtet, dass migrantische Arbeiterinnen durch beispielsweise ihre Vollzeitbeschäftigung auch einen emanzipatorischen Bruch des männlichen Ernährer-Modells bewirkten.

In Anbetracht der sogenannten wilden Streiks der 1970er Jahre, die ohne gewerkschaftliche Genehmigungen durchgeführt wurden, akzentuiert Kürten fest, dass neben den männlichen Streikenden auch viele migrantische Frauen beteiligt waren und sogar Proteste initiierten. Ein prägnantes Beispiel für letzteres ist die Arbeitsniederlegung bei der Firma *Auto- und Luftfahrt-Gerätebau KG Alfred Pierburg* in Neuss. Der Protest richtete sich gegen die schlechten Arbeitsbedingungen, die vergeschlechtlichte Lohndiskriminierung sowie die Leichtlohngruppe II, als unterste Lohngruppe, die weitgehend migrantische Arbeiterinnen betraf. Die *Gastarbeiterinnen* beteiligten sich somit an Arbeitskämpfen, machten auf Lohnunterschiede zwischen Frauen und Männern aufmerksam und stellten „selbstbewusste Forderungen" – streikende migrantische Frauen, die sich der Narrative der passiven Frau widersetzten.[^27] In Kürtens Auswertung von Presseberichten zum Pierburg-Streik wurde die Protestbeteiligung von Frauen allerdings in einem Drittel der Berichte kaum bis gar nicht erwähnt[^28] oder die migrantischen Arbeiterinnen als Mehrheit der Streikenden in den Hintergrund gerückt[^29].

<div style="width: 90%; margin: 2em auto 2em auto;">
<video controls style="width: 100%; display: block;">
  <source src="images/pierburg.mp4" type="video/mp4">
</video>
<div style="font-size: 0.75em; color: #555; font-style: italic; margin-top: 4px; margin-left: 3px;">
Migrantische Arbeiterinnen fordern beim Pierburg-Streik 1 D-Mark mehr Gehalt. © PIERBURG: IHR KAMPF IST UNSER KAMPF (DE 1974/75, Edith Schmidt/David Wittenberg), 00:07:44-00:08:49.
</div>
</div>

[^3]: Vgl. Kürten, Helena: „‚Gastarbeiterinnen im wilden Streik'. Zur Wahrnehmung von Arbeit, Migration und Geschlecht im Mediendiskurs der Bundesrepublik am Beispiel der rheinischen und westfälischen Metallindustrie". In: Wixforth, Harald (2017; Hg.): *Westfälische Forschungen*. Münster: Aschendorff Verlag. S. 501 f.

[^4]: Vgl. Mattes, Monika (2005): *„Gastarbeiterinnen" in der Bundesrepublik. Anwerbepolitik, Migration und Geschlecht in den 50er bis 70er Jahren*. Frankfurt am Main/New York: Campus Verlag. S. 59 f.

[^5]: Vgl. Mattes: *„Gastarbeiterinnen" in der Bundesrepublik*. S. 60; vgl. Hunn, Karin: ‚„Irgendwann kam das Deutschlandfieber auch in unsere Gegend...'. Türkische ‚Gastarbeiter' in der Bundesrepublik Deutschland – von der Anwerbung bis zur Rückkehrforderung". In: Motte, Jan/Ohlinger, Rainer (2004; Hg.): *Geschichte und Gedächtnis in der Einwanderungsgesellschaft. Migration zwischen historischer Rekonstruktion und Erinnerungspolitik*. Essen: Klartext Verlag. S. 79.

[^6]: Vgl. Märksch, Judith: „Geschlecht, Klasse und Ethnie auf dem Arbeitsmarkt der Bundesrepublik Deutschland 1965–1969". In: Loster-Schneider, Gudrun/Häusl, Maria/Horlacher, Stefan (2018; Hg.): *Gender-GraduateProjects III – Grenzen, Grenzgänge, Transgressionen*. Leipzig: Leipziger Universitätsverlag. S. 58.

[^7]: Vgl. Mattes: *„Gastarbeiterinnen" in der Bundesrepublik*. S. 28.

[^8]: Vgl. Märksch: „Geschlecht, Klasse und Ethnie". S. 53.

[^9]: Vgl. ibid. S. 58.

[^10]: Vgl. Mattes: *„Gastarbeiterinnen" in der Bundesrepublik*. S. 21.

[^11]: Kürten: ‚„Gastarbeiterinnen im wilden Streik'". S. 503.

[^12]: Vgl. Mattes: *„Gastarbeiterinnen" in der Bundesrepublik*. S. 75.

[^13]: Vgl. Kürten: ‚„Gastarbeiterinnen im wilden Streik'". S. 503.

[^14]: Mit Geschlechtercharakteren sind vermeintlich essentialistisch-vergeschlechtlichte Fähigkeiten und Eigenschaften (im Sinne von ‚typisch' weiblich/männlich) gemeint, die vor allem dazu dien(t)en, patriarchale Hierarchieordnungen aufrechtzuerhalten. Einschlägig dazu: Hausen, Karin: „Die Polarisierung der ‚Geschlechtercharaktere' – Eine Spiegelung der Dissoziation von Erwerbs- und Familienleben". In: Conze, Werner (1976; Hg.): *Sozialgeschichte der Familie in der Neuzeit Europas*. Stuttgart: Ernst Klett Verlag. S. 363–393.

[^15]: Vgl. Bednarz-Braun, Iris/Heß-Meining, Ulrike (2004): *Migration, Ethnie und Geschlecht*. Wiesbaden: VS Verlag für Sozialwissenschaften. S. 89.

[^16]: Vgl. Märksch: „Geschlecht, Klasse und Ethnie". S. 57.

[^17]: Ibid. S. 68 f.

[^18]: Vgl. ibid. S. 71.

[^19]: Vgl. ibid. S. 61, 69.

[^20]: Vgl. Märksch: „Geschlecht, Klasse und Ethnie". S. 53; vgl. Mattes: *„Gastarbeiterinnen" in der Bundesrepublik*. S. 96, 204 f.

[^21]: Vgl. Bednarz-Braun/Heß-Meining: *Migration, Ethnie und Geschlecht*. S. 73; vgl. Gümen, Sedef: „Das Soziale des Geschlechts. Frauenforschung und die Kategorie ‚Ethnizität'". In: Hark, Sabine (2001; Hg.): *Dis/Kontinuitäten: Feministische Theorie*. Opladen: Leske + Budrich. S. 147 f.

[^22]: Vgl. ibid. S. 76 f.

[^23]: Ibid. S. 77.

[^24]: Vgl. ibid. S. 80, 84, 91.

[^25]: Kürten: ‚„Gastarbeiterinnen im wilden Streik'". S. 499 f.

[^26]: Ibid. S. 500.

[^27]: Vgl. ibid. S. 499 f., 511.

[^28]: Vgl. ibid. S. 514 f.

[^29]: Vgl. ibid. S. 520.

[^30]: PIERBURG: IHR KAMPF IST UNSER KAMPF (DE 1974/75, Edith Schmidt/David Wittenberg), 00:07:44–00:08:49.
