---
title: "Quellenverzeichnis"
---

## Literaturverzeichnis

Assmann, Aleida (2006): „Geschlecht und kulturelles Gedächtnis". In: *Freiburger FrauenStudien: Zeitschrift für interdisziplinäre Frauenforschung*, Jg. 12/Nr. 2. S. 29–46.

Bednarz-Braun, Iris/Heß-Meining, Ulrike (2004): *Migration, Ethnie und Geschlecht*. Wiesbaden: VS Verlag für Sozialwissenschaften.

Connerton, Paul (2008): „Seven types of forgetting". In: *Memory Studies*, Jg. 1/Nr. 1. S. 59–71.

Erll, Astrid: „Medium des kollektiven Gedächtnisses: Ein (erinnerungs-)kulturwissenschaftlicher Kompaktbegriff". In: dies./Nünning, Ansgar (2004; Hg.): *Medien des kollektiven Gedächtnisses: Konstruktivität – Historizität – Kulturspezifität*. Berlin/New York: De Gruyter. S. 3–24.

Esposito, Elena: „Die Formen des Web-Gedächtnisses. Medien und soziales Gedächtnis". In: Lehmann, René/Öchsner, Florian/Sebald, Gerd (2013; Hg.): *Formen und Funktionen sozialen Erinnerns. Sozial- und kulturwissenschaftliche Analysen*. Wiesbaden: Springer VS. S. 91–103.

Gudehus, Christian: „Frederic C. Bartlett, Remembering". In: Leggewie, Claus et. al. (2012; Hg.): *Schlüsselwerke der Kulturwissenschaften*. Bielefeld: transcript Verlag. S. 155–157.

Gümen, Sedef: „Das Soziale des Geschlechts. Frauenforschung und die Kategorie ‚Ethnizität'". In: Hark, Sabine (2001; Hg.): *Dis/Kontinuitäten: Feministische Theorie*. Opladen: Leske + Budrich. S. 136–153.

Hunn, Karin: ‚„Irgendwann kam das Deutschlandfieber auch in unsere Gegend…'. Türkische ‚Gastarbeiter' in der Bundesrepublik Deutschland – von der Anwerbung bis zur Rückkehrforderung". In: Motte, Jan/Ohlinger, Rainer (2004; Hg.): *Geschichte und Gedächtnis in der Einwanderungsgesellschaft. Migration zwischen historischer Rekonstruktion und Erinnerungspolitik*. Essen: Klartext Verlag. S. 73–88.

Kürten, Helena: „‚Gastarbeiterinnen im wilden Streik'. Zur Wahrnehmung von Arbeit, Migration und Geschlecht im Mediendiskurs der Bundesrepublik am Beispiel der rheinischen und westfälischen Metallindustrie". In: Wixforth, Harald (2017; Hg.): *Westfälische Forschungen*. Münster: Aschendorff Verlag. S. 499–536.

Märksch, Judith: „Geschlecht, Klasse und Ethnie auf dem Arbeitsmarkt der Bundesrepublik Deutschland 1965–1969". In: Loster-Schneider, Gudrun/Häusl, Maria/Horlacher, Stefan (2018; Hg.): *GenderGraduateProjects III – Grenzen, Grenzgänge, Transgressionen*. Leipzig: Leipziger Universitätsverlag. S. 53–74.

Mattes, Monika (2005): *„Gastarbeiterinnen" in der Bundesrepublik. Anwerbepolitik, Migration und Geschlecht in den 50er bis 70er Jahren*. Frankfurt am Main/New York: Campus Verlag.

Motte, Jan/Ohlinger, Rainer: „Geschichte und Gedächtnis in der Einwanderungsgesellschaft. Einführende Betrachtungen". In: dies. (2004; Hg.): *Geschichte und Gedächtnis in der Einwanderungsgesellschaft. Migration zwischen historischer Rekonstruktion und Erinnerungspolitik*. Essen: Klartext Verlag. S. 7–16.

Münch, Felix: „Maurice Halbwachs, Les cadres sociaux de la mémoire". In: Leggewie, Claus et. al. (2012; Hg.): *Schlüsselwerke der Kulturwissenschaften*. Bielefeld: transcript Verlag. S. 153–155.

Ogden, Jessica/Summers, Edwards/Walker, Shawn (2024): „Know(ing) Infrastructure. The Wayback Machine as object and instrument of digital research". In: *Convergence: The International Journal of Research into New Media Technologies*, Jg. 30/Nr. 1. S. 167–189.

## Internetverzeichnis

Bundeszentrale für politische Bildung (o.J.): „Web 2.0". https://www.bpb.de/themen/medien-journalismus/medienpolitik/500735/web-2-0 (20.03.2026).

Internet Archives (o.J.): „About the Internet Archives". https://archive.org/about/ (20.03.2025).

Luber, Stefan/Litzel, Nico (2018): „Was ist ein Webcrawler?". In: *BigData-Insider*, 12.04.2018. https://www.bigdata-insider.de/was-ist-ein-webcrawler-a-704217/ (21.03.2026).

Statista (2025): „Market share of leading desktop search engines worldwide from January 2015 to October 2025". https://www.statista.com/statistics/216573/worldwide-market-share-of-search-engines/ (28.03.2026).

## Filmografie

PIERBURG: IHR KAMPF IST UNSER KAMPF DE 1974/75 F, S/W
49 Min. 
Regie/Montage: Edith Schmidt, David Wittenberg.
